# Generated by Django 5.1.4 on 2025-01-08 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='order',
        ),
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.IntegerField(choices=[(1, 'Percentage'), (2, 'Fixed'), (3, 'Subtotal Percentage'), (4, 'Subtotal Fixed')], default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CouponUse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.order')),
            ],
            options={
                'db_table': 'coupon_use',
            },
        ),
    ]
