# Generated by Django 5.1.4 on 2025-01-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_slug_ticket_code_ticket_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_active',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
